### PR TITLE
fix(webapp): fail chmod +x loudly when the VFS has no exec bit

### LINKED ISSUE #3109: chmod +x reports success but leaves the mode unchanged; ./script then fails with a bare "Permission denied"
## Measured

```
$ printf '#!/bin/bash\necho ran-ok\n' > /tmp/execbit-probe.sh
$ ls -l /tmp/execbit-probe.sh
-rw-r--r-- 1 user user 24 Sep 15 03:12 /tmp/execbit-probe.sh
$ chmod +x /tmp/execbit-probe.sh          # exit 0, no output
$ ls -l /tmp/execbit-probe.sh
-rw-r--r-- 1 user user 24 Sep 15 03:12 /tmp/execbit-probe.sh   # unchanged
$ ./execbit-probe.sh
bash: ./execbit-probe.sh: Permission denied
$ bash /tmp/execbit-probe.sh
ran-ok
```

The VFS carries no executable bit, so `./script` can never work and `bash script` always does. That is a reasonable limitation. The bug is that `chmod` **reports success while doing nothing**, and the resulting failure message names a cause that does not exist.

## Asks

1. `chmod` should not silently succeed when it cannot change the mode. Either apply the change or fail loudly (`EOPNOTSUPP` / "the VFS does not support an executable bit"). A no-op that returns 0 is the actual defect.
2. When execution fails with `EACCES` on a VFS file whose first bytes are a `#!` shebang, the shell could add a hint: `run it with the interpreter, e.g. bash <file>`.

## Why it is worth fixing despite being cosmetic

The silent no-op does not merely cost a turn — it manufactures a **false causal model that outlives the session**. Two separate sessions hit `Permission denied` on a `/tmp` helper; one added `chmod +x` and it still failed. The conclusion recorded in durable agent memory was:

> Writing an executable helper to the shared `/tmp` root failed. Use a shell function or a private scratch dir.

Both the cause and the remedy in that note are wrong: the shared root is irrelevant, and a private directory would have failed identically. The note survived until a control test (`chmod +x`, then re-`stat`) was actually run. A silent no-op is worse than an error precisely because the first plausible mechanism gets written down as fact.

Related: #3108 proposes reporting exec-bit support as one of the probed mount capabilities, which would let tooling know this up front rather than inferring it from a failure.

### PR DESCRIPTION
**Pull request by trieloff**
Closes #3109.

## Summary

`chmod +x` on a VFS file used to exit 0 with no output while `ls -l` stayed `-rw-r--r--` and `./script` failed with a bare Permission denied. `chmod` now fails with `EOPNOTSUPP` and a diagnostic that the VFS does not store an executable bit. `bash file` still runs. `./script` on a shebang file hints at the interpreter.

## Why

**Repro**
1. `printf '#!/bin/bash\necho ran-ok\n' > /tmp/execbit-probe.sh`
2. `chmod +x /tmp/execbit-probe.sh` — used to exit 0 with no output
3. `ls -l` unchanged; `./execbit-probe.sh` → Permission denied; `bash /tmp/execbit-probe.sh` → `ran-ok`

Silent success manufactured a false causal model (agents blamed `/tmp` as a special shared root) that outlived the session.

Related: #3108 (report exec-bit support as a probed mount capability). This PR does not implement that probe.

## Approach / Implementation notes

- `VfsAdapter.chmod()` throws `EOPNOTSUPP` (ENOENT if missing) instead of a silent no-op.
- just-bash's `chmod` maps every FS error to `cannot access: No such file`. A supplemental overlay reports the real errno so agents do not treat a mode-unsupported file as missing.
- `mktemp` keeps the unique name on `EOPNOTSUPP`/`ENOTSUP`/`ENOSYS` (privacy was never available). `EPERM` still takes the entry back.
- Optional shebang hint on `./file` Permission denied, loaded on that error path so it stays out of the kernel-worker first-load graph.
- Node `chmodSync` remains the documented existence-gated no-op. Dual-mode: CLI and extension share `VfsAdapter` + the overlay.

## Cross-cutting impact

- **Floats**: CLI, Chrome extension, Electron, worker — same VFS adapter and shell overlay.
- **Other callers**: `mktemp` was the production caller of `fs.chmod`; it now treats unsupported modes as success-for-unique-name.
- **`umask`**: no longer points at `chmod` as the working alternative.

## Test plan

- [x] `npm run verify`
- [x] `npm run typecheck`
- [x] `npm run test` — 22235 passing; one 5s timeout flake in `check-touched-exemptions.test.mjs` (passes in isolation, unrelated)
- [x] `npx vitest run packages/webapp/tests/shell/chmod-exec-bit.test.ts` and overlay/adapter tests
- [x] `npm run build` (includes chrome-extension)
- [x] first-load: worker +0.6 kB vs merge-base, at the 4306 kB ceiling (chmod overlay + shebang hint are lazy)
- [x] New tests: chmod +x → non-zero + `EOPNOTSUPP`; mode unchanged; `bash file` still runs; `./script` hints at the interpreter
- [x] Existing chmod tests stay (`chmodSync` no-op, mktemp no-op backend, mktemp EPERM take-back)

**Pre-existing failures**: `git-commands.test.ts` rebase merge-commit test timed out at 5s under coverage load; passes in isolation.

## Documentation

- [x] `docs/shell-reference.md`
- [x] `packages/vfs-root/shared/CLAUDE.md` (agent-facing)
- [x] mktemp / umask help text

## Risk & rollback

Blast radius is the shell `chmod` path on every float. Revert this PR. No persisted state.

## Checklist

- [x] Commits are focused and package-local
- [x] No hand-edited files under `dist/`
- [x] No secrets in the diff
- [x] Shell-command change is reflected in docs

### CODE REVIEW

File: packages/webapp/src/shell/vfs-adapter.ts [hunk 1]
```diff
@@ -714,8 +714,25 @@ export class VfsAdapter implements IFileSystem {
...
 
-  async chmod(_path: string, _mode: number): Promise<void> {
-    // Our VFS doesn't track permissions — no-op
+  async chmod(path: string, _mode: number): Promise<void> {
+    return this.trusted(async () => {
+      const normalized = normalizePath(path);
+      const exists =
+        this.virtualUsrStat(normalized) !== null || (await this.vfs.exists(normalized));
+      if (!exists) {
+        throw new FsError('ENOENT', 'no such file or directory', normalized);
```
[the remark this answers is not in the document]
Comment (trieloff) [reply packages/webapp/src/shell/vfs-adapter.ts]: Fixed: `chmod` now `stat()`s the target so a mount `EIO` is not rewritten as `ENOENT`. `mktemp` therefore will not take the unique name back on a transient I/O error.

File: packages/webapp/src/shell/shebang-exec-hint.ts [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+): Promise<T> {
+  if (result.exitCode === 0) return result;
+  if (result.stderr.includes(HINT_ALREADY)) return result;
+  const match = result.stderr.match(PERM_DENIED);
+  if (!match) return result;
+  const operand = match[1];
+  const path = fs.resolvePath(cwd, operand);
+  let content: string;
+  try {
+    content = await fs.readFile(path);
```
[the remark this answers is not in the document]
Comment (trieloff) [reply packages/webapp/src/shell/shebang-exec-hint.ts]: Fixed: the hint path now prefers `readFileRange(path, 0, 256)` so `./large-file` does not materialize the whole file.

File: packages/webapp/src/shell/supplemental-commands/chmod/run.ts [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+async function chmodPath(ctx: CommandContext, file: string, spec: string): Promise<void> {
+  const path = ctx.fs.resolvePath(ctx.cwd, file);
+  const st = await ctx.fs.stat(path);
+  await ctx.fs.chmod(path, requestedMode(spec, st.mode));
+}
+
+export async function runChmod(args: string[], ctx: CommandContext): Promise<CmdResult> {
+  if (args.includes('--help')) return { stdout: HELP, stderr: '', exitCode: 0 };
```
[the remark this answers is not in the document]
Comment (trieloff) [reply packages/webapp/src/shell/supplemental-commands/chmod/run.ts]: Fixed: `--help` is only a help request before `--`. `chmod +x -- --help` now chmods the file named `--help`.

File: packages/webapp/src/shell/shebang-exec-hint.ts [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+
+const HINT_ALREADY = 'run it with the interpreter';
+
+function interpreterFromShebang(content: string): string {
+  const line = content.split(/\r?\n/, 1)[0] ?? '';
+  if (!line.startsWith('#!')) return 'bash';
+  const tokens = line.slice(2).trim().split(/\s+/).filter(Boolean);
+  if (tokens.length === 0) return 'bash';
+  const bin = tokens[0].split('/').pop() ?? 'bash';
+  if (bin === 'env' && tokens[1]) return tokens[1];
```
[the remark this answers is not in the document]
Comment (trieloff) [reply packages/webapp/src/shell/shebang-exec-hint.ts]: Fixed: `env` options (`-S`, `-u`, assignments) are skipped so `#!/usr/bin/env -S python3 -u` hints `python3`, not `-S`.
